[build]
  publish = "."
  command = ""
  
[build.environment]
  NODE_VERSION = "18"

# Form handling for data collection
[[forms]]
  name = "expense-form"
  action = "/admin.html"
  method = "POST"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Cache control for different file types
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600, stale-while-revalidate=86400"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Compression
[[headers]]
  for = "/*"
  [headers.values]
    Content-Encoding = "gzip"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API redirects (for future backend integration)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
